server:
  port: 18080
  servlet:
    context-path: /api

spring:
  mvc:
    async:
      request-timeout: -1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    hikari:
      connection-timeout: 50000

elasticsearch:
  uris: "localhost:9200"

similarity:
  max-result: 15
  min-score: 0.65
