name: CI

on: [ push ]

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 10
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.8.0
        with:
          arguments: build

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Execute Gradle Coverage
        run: ./gradlew check

      - name: Execute Gradle Coverage
        if: runner.os == 'macOS'
        run: bash <(curl -s https://codecov.io/bash)
